pulsar:
  topic:
    test-topic: persistent://public/default/test-topic
    test-topicA: persistent://public/default/test-topicA
    test-topicB: persistent://public/default/test-topicB
    test-topicC: persistent://public/default/test-topicB
  client:
    service-pulsar-url: pulsar://127.0.0.1:6650
    service-http-url: http://127.0.0.1:8080
#    service-pulsar-url: pulsar://127.0.0.1:16650,127.0.0.1:26650,127.0.0.1:36650
#    service-http-url: http://127.0.0.1:18080,127.0.0.1:28080,127.0.0.1:38080


